# Generated by Django 4.1.5 on 2023-01-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoringurls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlslist',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
