# Generated by Django 4.1.5 on 2023-01-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoringurls', '0002_urlslist_year_in_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlslist',
            name='year_in_school',
            field=models.CharField(choices=[('1', 'ACTIVE'), ('0', 'DOWN')], max_length=1),
        ),
    ]
