# Generated by Django 4.1.5 on 2023-01-03 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoringurls', '0003_alter_urlslist_year_in_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlslist',
            old_name='year_in_school',
            new_name='status',
        ),
    ]
