# Generated by Django 4.1.5 on 2023-01-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoringurls', '0004_rename_year_in_school_urlslist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlslist',
            name='url_name',
            field=models.URLField(),
        ),
    ]
