# Generated by Django 4.1.5 on 2023-01-03 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoringurls', '0005_alter_urlslist_url_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='urlshistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url_name', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('0', 'DOWN')], max_length=1)),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Monitoringurls.urlslist')),
            ],
        ),
    ]
