# Generated by Django 4.1.5 on 2023-01-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoringurls', '0006_urlshistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshistory',
            name='url_name',
        ),
    ]
