# Generated by Django 4.1.1 on 2023-01-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoringurls', '0008_alter_urlslist_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlshistory',
            old_name='url_id',
            new_name='url_name',
        ),
        migrations.AlterField(
            model_name='urlshistory',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DOWN', 'DOWN')], max_length=6),
        ),
    ]
