# Generated by Django 4.1.1 on 2023-01-04 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoringurls', '0010_rename_url_name_urlshistory_urlslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshistory',
            name='urlslist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Monitoringurls.urlslist'),
        ),
    ]
