# Generated by Django 4.1.1 on 2023-01-04 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Monitoringurls', '0012_alter_urlshistory_urlslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlslist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
