# Generated by Django 4.1.1 on 2023-01-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoringurls', '0013_alter_urlslist_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='deletedurls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url_name', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
