# Generated by Django 4.1.1 on 2023-01-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoringurls', '0015_deletedurls_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedurls',
            name='created_at',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='urlshistory',
            name='created_at',
            field=models.CharField(max_length=100),
        ),
    ]
