# Generated by Django 4.1.5 on 2023-01-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoringurls', '0016_alter_deletedurls_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshistory',
            name='minutes',
            field=models.IntegerField(default=1),
        ),
    ]
