# Generated by Django 4.1.5 on 2023-01-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoringurls', '0017_urlshistory_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshistory',
            name='minutes',
            field=models.IntegerField(),
        ),
    ]
