# Generated by Django 4.1.5 on 2023-01-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoringurls', '0018_alter_urlshistory_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshistory',
            name='minutes',
        ),
    ]
